vulnerabilities:
  # Reported: https://issuetracker.google.com/issues/482060894
  - id: CVE-2021-22569
    purls:
      - "pkg:maven/com.google.protobuf/protobuf-java"
    statement: "Internal protobuf dependency in Kotlin compiler. Low risk in CI environment."
  # Reported: https://issuetracker.google.com/issues/482060894
  - id: CVE-2024-7254
    purls:
      - "pkg:maven/com.google.protobuf/protobuf-java"
    statement: "StackOverflow vulnerability in protobuf parser. Not exploitable during standard Android builds."
