format: table
exit-code: 1
ignorefile: .github/.trivyignore.yaml
severity:
  - CRITICAL
  - HIGH
vulnerability:
  ignore-unfixed: true
db:
  java-repository:
    - public.ecr.aws/aquasecurity/trivy-java-db:1
    - mirror.gcr.io/aquasec/trivy-java-db:1
    - ghcr.io/aquasecurity/trivy-java-db:1
  repository:
    - public.ecr.aws/aquasecurity/trivy-db:2
    - mirror.gcr.io/aquasec/trivy-db:2
    - ghcr.io/aquasecurity/trivy-db:2
