name: 'Generate Version'
description: 'If version_tag is empty calculate next version string based on CalVer and Conventional Commits'

inputs:
  version_tag:
    description: 'Current tag name (if triggered by a tag push). If set will not generate new version.'
    required: true
  minor_types:
    description: 'List of commit types for minor bumps (comma or newline separated, e.g. feat, perf)'
    required: true
  patch_types:
    description: 'List of commit types for patch bumps (comma or newline separated, e.g. fix, refactor, style, test)'
    required: true

outputs:
  version:
    description: 'The (current or next) version string (e.g. v2026.1.0)'
    value: ${{ steps.generate-version.outputs.version }}
  reason:
    description: 'The reason for the version bump'
    value: ${{ steps.generate-version.outputs.reason }}
  bumped:
    description: 'Boolean flag indicating if a version bump occurred'
    value: ${{ steps.generate-version.outputs.bumped }}

runs:
  using: 'composite'
  steps:
    - id: tag-trigger
      if: ${{ inputs.version_tag != '' }}
      shell: bash
      run: |
        echo "version=${{ inputs.version_tag }}" >> "$GITHUB_OUTPUT"
        echo "reason=tag-trigger" >> "$GITHUB_OUTPUT"
        echo "bumped=false" >> "$GITHUB_OUTPUT"
    - id: generate-version
      if: ${{ inputs.version_tag == '' }}
      shell: bash
      run: |
        json_output=$("${{ github.action_path }}/scripts/generate-version.sh" \
          "${{ inputs.minor_types }}" \
          "${{ inputs.patch_types }}")

        echo "Result: $json_output"

        echo "version=$(echo "$json_output" | jq -r '.version')" >> "$GITHUB_OUTPUT"
        echo "reason=$(echo "$json_output" | jq -r '.reason')" >> "$GITHUB_OUTPUT"
        echo "bumped=$(echo "$json_output" | jq -r '.bumped')" >> "$GITHUB_OUTPUT"
