name: 'Image Analyzer'
description: 'Installs dive and analyzes a docker image for efficiency using bash scripts'

inputs:
  image-ref:
    description: 'The image to analyze'
    required: true
  dive-ci-config:
    description: 'Path to .dive-ci config'
    required: true
  dive-version:
    description: 'The version of dive to use (normalizes leading v)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Install Dive'
      shell: bash
      run: |
        "${{ github.action_path }}/scripts/install-dive.sh" "${{ inputs.dive-version }}"

    - name: 'Analyze Image'
      id: analyze
      shell: bash
      run: |
        "${{ github.action_path }}/scripts/analyze-image.sh" \
          "${{ inputs.image-ref }}" \
          "${{ inputs.dive-ci-config }}"
