name: 'Gradle Integration Smoke Test'
description: 'Orchestrates the Docker-based Gradle integration test'

inputs:
  image_ref:
    description: 'Docker Image Tag to be tested'
    required: true
  run_as_uid:
    description: 'UID for the container process'
    default: '1234'
  run_as_gid:
    description: 'GID for the container process'
    default: '0'

runs:
  using: 'composite'
  steps:
    - name: Run Orchestrator Script
      shell: bash
      run: |
        "${{ github.action_path }}/scripts/run-integration-test.sh" \
          "${{ inputs.image_ref }}" \
          "${{ inputs.run_as_uid }}" \
          "${{ inputs.run_as_gid }}" \
          "${{ github.action_path }}"
