name: 'Gradle Integration Smoke Test'
description: 'Orchestrates the Docker-based Gradle integration test'

inputs:
  image-ref:
    description: 'Docker Image Tag to be tested'
    required: true
  run-as-uid:
    description: 'UID for the container process'
    default: '1234'
  run-as-gid:
    description: 'GID for the container process'
    default: '0'

runs:
  using: 'composite'
  steps:
    - name: Run Orchestrator Script
      shell: bash
      run: |
        "${{ github.action_path }}/scripts/run-integration-test.sh" \
          "${{ inputs.image-ref }}" \
          "${{ inputs.run-as-uid }}" \
          "${{ inputs.run-as-gid }}" \
          "${{ github.action_path }}"
