name: 'Renovate Config Validator'
description: 'Validates all Renovate config files found inside default locations using npx.'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      with:
        node-version: 'lts/*'

    - name: 'Validate Renovate config'
      shell: bash
      run: |
        "${{ github.action_path }}/scripts/run-renovate-config-validator.sh"
