name: 'Renovate Config Validator'
description: 'Validates all Renovate config files found inside default locations using npx.'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version: 'lts/*'

    - name: 'Validate Renovate config'
      shell: bash
      run: |
        "${{ github.action_path }}/scripts/run-renovate-config-validator.sh"
