name: 'JDK Version Extractor'
description: 'Extracts JDK image aliases from a Dockerfile using a bash script'

inputs:
  dockerfile_path:
    description: 'Path to the Dockerfile'
    required: false
    default: 'Dockerfile'

outputs:
  versions_json:
    description: 'JSON array of jdk names'
    value: ${{ steps.extract-jdk-versions.outputs.json }}

runs:
  using: 'composite'
  steps:
    - id: extract-jdk-versions
      shell: bash
      run: |
        json_result=$("${{ github.action_path }}/scripts/extract-jdk-versions.sh" "${{ inputs.dockerfile_path }}")
        echo "Result: $json_result"
        echo "json=$json_result" >> "$GITHUB_OUTPUT"
