name: 'Android Platform Version Fetcher'
description: 'Fetches the latest Android platform versions'

inputs:
  max_version:
    description: 'The highest Android API level to include (e.g. 36.1)'
    required: true
  max_major_versions_count:
    description: 'How many major versions to include'
    required: false
    default: '3'

outputs:
  versions_json:
    description: 'The latest platform versions as a JSON array'
    value: ${{ steps.fetch-versions.outputs.json }}

runs:
  using: 'composite'
  steps:
    - id: fetch-versions
      shell: bash
      run: |
        json_result=$("${{ github.action_path }}/scripts/fetch-versions.sh" \
          "${{ inputs.max_version }}" \
          "${{ inputs.max_major_versions_count }}")
        echo "Result: $json_result"
        echo "json=$json_result" >> "$GITHUB_OUTPUT"
