name: "Android Image Pipeline"

on:
  release:
    types: [ created ]
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

concurrency:
  # Tags get a unique run_id to prevent cancellation during release.
  # Other events (main/PRs) use the branch name to allow canceling outdated builds.
  group: >-
    ${{ startsWith(github.ref, 'refs/tags/') && github.run_id || github.workflow }}-${{ github.head_ref || github.ref }}
  # Only cancel running jobs if the current event is NOT a tag push
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/') }}

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  setup:
    name: "🛠️ Prepare Build Matrix"
    runs-on: ubuntu-24.04
    outputs:
      jdk_versions: ${{ steps.jdk-versions-extractor.outputs.versions_json }}
      latest_jdk_version: ${{ steps.jdk-versions-extractor.outputs.latest_version }}
      platform_versions: ${{ steps.android-platform-versions-fetcher.outputs.versions_json }}
      latest_platform_version: ${{ steps.android-platform-versions-fetcher.outputs.latest_version }}
      cmdline_tools_id: ${{ steps.cmdline-tools-id-fetcher.outputs.cmdline_tools_id }}
      platform_tools_version: ${{ env.ANDROID_PLATFORM_TOOLS_VERSION }}
      build_tools_version: ${{ env.ANDROID_BUILD_TOOLS_VERSION }}
      environment: ${{ steps.set-environment.outputs.environment }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: "Set GitHub Deployment Environment"
        id: set-environment
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "environment=release" >> "$GITHUB_OUTPUT"
          else
            echo "environment=preview" >> "$GITHUB_OUTPUT"
          fi

      - name: "Prepare environment variables"
        run: |
          grep -v '^#' versions.env >> "$GITHUB_ENV"

      - name: "Get supported jdk versions from Dockerfile"
        id: jdk-versions-extractor
        uses: ./.github/actions/jdk-versions-extractor
        with:
          dockerfile_path: 'Dockerfile'

      - name: "Get command-line tools ID based on version"
        id: cmdline-tools-id-fetcher
        uses: ./.github/actions/cmdline-tools-id-fetcher
        with:
          version: ${{ env.ANDROID_CMDLINE_TOOLS_VERSION }}

      - name: "Get latest Android Platform versions"
        id: android-platform-versions-fetcher
        uses: ./.github/actions/android-platform-versions-fetcher
        with:
          max_version: ${{ env.ANDROID_PLATFORM_MAX_VERSION }}

  versioning:
    name: "🏷️ Versioning"
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.generate-version.outputs.version }}
      bumped: ${{ steps.generate-version.outputs.bumped }}
      create_release_tag: ${{ steps.generate-version.outputs.create_release_tag }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: ./.github/actions/generate-version
        id: generate-version
        with:
          version_tag: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
          minor_types: 'feat'
          patch_types: 'fix'

  build:
    needs: [ setup, versioning ]
    runs-on: ubuntu-24.04
    environment: ${{ needs.setup.outputs.environment }}
    name: >
      ${{ needs.setup.outputs.environment == 'release' && '📦 Build' || '🔬 Validate' }}
      (JDK ${{ matrix.jdk_version }}, Android ${{ matrix.platform_version }})
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        jdk_version: ${{
          fromJson(
          needs.setup.outputs.environment == 'release' &&
          needs.setup.outputs.jdk_versions ||
          format('["{0}"]', needs.setup.outputs.latest_jdk_version)
          ) }}
        platform_version: ${{
          fromJson(
          needs.setup.outputs.environment == 'release' &&
          needs.setup.outputs.platform_versions ||
          format('["{0}"]', needs.setup.outputs.latest_platform_version)
          ) }}

    env:
      IMAGE_VERSION: >-
        ${{ needs.versioning.outputs.version }}${{ needs.setup.outputs.environment == 'release' && '' || '-dev' }}
      DOCKER_HUB_IMAGE_NAME: g00fy2/alpaquita-android
      DOCKER_HUB_USERNAME: g00fy2
      GHCR_IMAGE_NAME: g00fy2/alpaquita-android
      DOCKER_BUILD_ARGS: |
        BASE_IMAGE=jdk${{ matrix.jdk_version }}
        ANDROID_CMDLINE_TOOLS_ID=${{ needs.setup.outputs.cmdline_tools_id }}
        ANDROID_PLATFORM_TOOLS_VERSION=${{ needs.setup.outputs.platform_tools_version }}
        ANDROID_BUILD_TOOLS_VERSION=${{ needs.setup.outputs.build_tools_version }}
        ANDROID_PLATFORM_VERSION=${{ matrix.platform_version }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: "Docker metadata"
        id: docker-metadata
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6
        with:
          images: |
            ${{ env.DOCKER_HUB_IMAGE_NAME }}
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.IMAGE_VERSION }}-android-${{ matrix.platform_version }}-jdk${{ matrix.jdk_version }}
            type=raw,value=android-${{ matrix.platform_version }}-jdk${{ matrix.jdk_version }}
            type=raw,value=latest,enable=${{
              matrix.platform_version == needs.setup.outputs.latest_platform_version &&
              matrix.jdk_version == needs.setup.outputs.latest_jdk_version
            }}

      - name: "Set Docker image reference"
        id: set-image-ref
        run: |
          tag=$(echo "${{ steps.docker-metadata.outputs.tag-names }}" | head -n 1)
          echo "image=${{ env.DOCKER_HUB_IMAGE_NAME }}:$tag" >> "$GITHUB_OUTPUT"

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4
        env:
          DOCKER_BUILDX_VERSION: v0.34.0
          DOCKER_BUILDKIT_VERSION: v0.30.0
        with:
          version: ${{ env.DOCKER_BUILDX_VERSION }}
          driver-opts: image=moby/buildkit:${{ env.DOCKER_BUILDKIT_VERSION }}

      - name: "Build Docker Image without pushing"
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          context: .
          load: true
          platforms: linux/amd64
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          build-args: ${{ env.DOCKER_BUILD_ARGS }}

      - name: "Run Dive"
        id: dive-analyze
        uses: ./.github/actions/dive-analyze
        env:
          DIVE_VERSION: v0.13.1
        with:
          image-ref: ${{ steps.set-image-ref.outputs.image }}
          dive-ci-config: .github/.dive-ci.yaml
          dive-version: ${{ env.DIVE_VERSION }}

      - name: "Run Trivy"
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        env:
          TRIVY_DISABLE_VEX_NOTICE: true
        with:
          image-ref: ${{ steps.set-image-ref.outputs.image }}
          scan-type: image
          trivy-config: .github/trivy.yaml

      - name: "Run image and generate Manifest"
        id: generate-manifest
        uses: ./.github/actions/generate-manifest
        with:
          image-ref: ${{ steps.set-image-ref.outputs.image }}

      - name: "Upload manifest artifact"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: manifest-jdk${{ matrix.jdk_version }}-android${{ matrix.platform_version }}
          path: ${{ steps.generate-manifest.outputs.manifest_path }}
          if-no-files-found: error
          archive: false

      - name: "Run Android Gradle Build smoke test"
        uses: ./.github/actions/android-build-smoke-test
        with:
          image-ref: ${{ steps.set-image-ref.outputs.image }}

      - name: "Login to Docker Hub"
        if: ${{ needs.setup.outputs.environment == 'release' }}
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: "Login to GitHub Container Registry"
        if: ${{ needs.setup.outputs.environment == 'release' }}
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and push Docker Images"
        if: ${{ needs.setup.outputs.environment == 'release' }}
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          build-args: ${{ env.DOCKER_BUILD_ARGS }}
          outputs: type=registry,compression=zstd,compression-level=9,force-compression=true

  build-summary:
    name: "🏁 Build Matrix Complete"
    runs-on: ubuntu-24.04
    if: always()
    needs: build
    steps:
      - name: "Consolidate build status"
        run: |
          if [ "${{ needs.build.result }}" != "success" ]; then
            exit 1
          fi

  create-tag-or-github-release:
    name: "🚀 Conditionally create Tag or GitHub Release"
    runs-on: ubuntu-24.04
    needs: [ setup, versioning, build-summary ]
    if: >-
      ${{ success() && (needs.versioning.outputs.create_release_tag == 'true' ||
      needs.setup.outputs.environment == 'release') }}
    environment: ${{ needs.setup.outputs.environment }}
    permissions:
      contents: write
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: "Merge matrix manifests"
        id: merge-manifests
        uses: ./.github/actions/merge-matrix-manifests
        with:
          version: ${{ env.IMAGE_VERSION }}

      - name: "Create GitHub release"
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1
        with:
          allowUpdates: true
          bodyFile: ${{ steps.merge-manifests.outputs.merged_manifests_path }}
          prerelease: ${{ needs.setup.outputs.environment != 'release' }}
          generateReleaseNotes: true
          tag: ${{ needs.versioning.outputs.version }}
          token: ${{ secrets.GH_PAT_TOKEN }}
