name: "Linting"

on:
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  sh-checker:
    name: "Shell Checker (shellcheck, shfmt, checkbashisms)"
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: "Run sh-checker"
        uses: luizm/action-sh-checker@883217215b11c1fabbf00eb1a9a041f62d74c744 # v0.10.0
        with:
          sh_checker_checkbashisms_enable: true

  yamllint:
    name: "Yamllint"
    runs-on: ubuntu-24.04
    env:
      YAMLLINT_VERSION: 1.38.0
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: "Check for .yml extensions"
        run: |
          find . -type f -name "*.yml" | grep . && { echo "Error: Use .yaml instead of .yml"; exit 1; } || exit 0

      - name: "Install yamllint"
        run: pip install yamllint==${{ env.YAMLLINT_VERSION }}

      - name: "Run yamllint"
        run: yamllint -c .github/.yamllint.yaml .

  renovate-config-validator:
    name: "Renovate config validator"
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: "Run Renovate config validator"
        uses: ./.github/actions/renovate-config-validator

  actionlint:
    name: "Actionlint"
    runs-on: ubuntu-24.04
    env:
      ACTIONLINT_VERSION: 1.7.11
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: "Install actionlint"
        id: install-actionlint
        run: |
          bash <(curl -sL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) \
          ${{ env.ACTIONLINT_VERSION }}

      - name: "Run actionlint"
        run: ${{ steps.install-actionlint.outputs.executable }} -color

  hadolint:
    name: "Hadolint"
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: "Run Hadolint"
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          verbose: true

      - name: "Hadolint Results"
        if: always()
        run: echo "${HADOLINT_RESULTS:-No issues found.}"

  docker-build-checks:
    name: "Docker Buildx Checks"
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4
        env:
          DOCKER_BUILDX_VERSION: v0.32.1
          DOCKER_BUILDKIT_VERSION: v0.28.0
        with:
          version: ${{ env.DOCKER_BUILDX_VERSION }}
          driver-opts: image=moby/buildkit:${{ env.DOCKER_BUILDKIT_VERSION }}

      - name: "Run Buildx Checks"
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: .
          call: check
          platforms: linux/amd64,linux/arm64
